name: untare
description: Unofficial app for Tandoor Recipes

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2+8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_phoenix: ^1.0.0
  cached_network_image: ^3.2.1
  shimmer: ^3.0.0
  settings_ui: ^2.0.2
  sliver_tools: ^0.2.5
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  flutter_form_builder: 9.3.0
  form_builder_validators: ^11.0.0
  form_builder_extra_fields: ^10.1.0
  form_builder_image_picker: ^4.0.0
  flutter_slidable: ^3.0.0
  intl: ^0.19.0
  grouped_list: ^5.1.2
  configurable_expansion_tile_null_safety: ^3.0.0
  lazy_load_scrollview: 1.3.0
  drag_and_drop_lists: ^0.4.1
  workmanager: ^0.5.0
  flutter_colorpicker: ^1.0.3
  wakelock: ^0.6.2
  path_provider: ^2.0.11
  collapsible: ^1.0.0
  share_plus: ^6.3.4
  fraction: ^5.0.2
  flutter_markdown: ^0.7.3
  url_launcher: ^6.2.2
  receive_sharing_intent: ^1.7.0
  dynamic_color: ^1.7.0

dependency_overrides:
  flutter_chips_input:
    git: https://github.com/phantomate/flutter_chips_input

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.12.0
  rename: ^3.0.1

flutter_icons:
  android: "app_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/app_icon.png"
  adaptive_icon_background: "#ddbf86"
  adaptive_icon_foreground: "images/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
